name: donna
description: Accounting Software.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter: 
    sdk: flutter

  cupertino_icons: ^1.0.2
  bitsdojo_window: ^0.1.5
  flutter_launcher_icons: ^0.10.0
  http: ^0.13.5
  date_format: ^2.0.7
  sticky_headers: ^0.3.0+2
  flutter_svg: ^1.1.5
  hovering: ^1.0.4
  system_theme: ^2.0.0
  moor: ^4.6.1+1
  sqflite: ^2.1.0+1
  sqflite_common_ffi: ^2.1.1+1
  flutter_staggered_grid_view: ^0.4.0-nullsafety.3
  

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/donna-logo.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/icons/donna-logo.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "assets/icons/donna-logo.png"
    icon_size: 48 # min:48, max:256, default: 48

flutter:

  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/

  fonts:
    - family:  Segoe UI
      fonts:
      - asset: assets/fonts/Segoe UI/segoeuil.ttf 
        weight: 100
      - asset: assets/fonts/Segoe UI/segoeuisl.ttf 
        weight: 200
      - asset: assets/fonts/Segoe UI/segoeui.ttf 
        weight: 300
      - asset: assets/fonts/Segoe UI/seguisb.ttf 
        weight: 400
      - asset: assets/fonts/Segoe UI/segoeuib.ttf 
        weight: 500
      - asset: assets/fonts/Segoe UI/seguibl.ttf 
        weight: 600
      - asset: assets/fonts/Segoe UI/seguili.ttf 
        style: italic
        weight: 100
      - asset: assets/fonts/Segoe UI/seguisli.ttf
        style: italic
        weight: 200
      - asset: assets/fonts/Segoe UI/segoeuii.ttf 
        style: italic
        weight: 300
      - asset: assets/fonts/Segoe UI/seguisbi.ttf 
        style: italic
        weight: 400
      - asset: assets/fonts/Segoe UI/segoeuiz.ttf 
        style: italic
        weight: 500
      - asset: assets/fonts/Segoe UI/seguibli.ttf 
        style: italic
        weight: 600